apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: poc-template-scaffolder
  title: POC template
  description: POC template
  tags:
    - recommended
    - python
spec:
  owner: web@example.com
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.
